plugins {
    id 'java'
    id 'application'
}

group = 'com.runnerqueen'
version = '1.0.0'
sourceCompatibility = '11'

repositories {
    mavenCentral()
}

ext {
    gdxVersion = '1.12.1'
}

dependencies {
    implementation "com.badlogicgames.gdx:gdx:${gdxVersion}"
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:${gdxVersion}"
    implementation "com.badlogicgames.gdx:gdx-platform:${gdxVersion}:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-box2d:${gdxVersion}"
    implementation "com.badlogicgames.gdx:gdx-box2d-platform:${gdxVersion}:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-bullet:${gdxVersion}"
    implementation "com.badlogicgames.gdx:gdx-bullet-platform:${gdxVersion}:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-freetype:${gdxVersion}"
    implementation "com.badlogicgames.gdx:gdx-freetype-platform:${gdxVersion}:natives-desktop"
}

application {
    mainClass = 'com.runnerqueen.RunnerQueenGame'
}

tasks.register('run', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.runnerqueen.RunnerQueenGame'
}
